### ISSUE TITLE
The command is installed and stuck

### ISSUE THREAD

**Issue by imjianbing** [pvtl/voyager-frontend#28]
hello , The command is installed and stuck
composer dump-autoload && php artisan voyager-frontend:install

  voyager composer dump-autoload && php artisan voyager-frontend:install
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: fideloper/proxy
Discovered Package: laravel/tinker
Discovered Package: nunomaduro/collision
Discovered Package: larapack/voyager-hooks
Discovered Package: arrilot/laravel-widgets
Discovered Package: intervention/image
Discovered Package: tcg/voyager
Discovered Package: laravel/scout
Discovered Package: teamtnt/laravel-scout-tntsearch-driver
Discovered Package: spatie/laravel-sitemap
Discovered Package: pvtl/voyager-blog
Discovered Package: pvtl/voyager-pages
Discovered Package: pvtl/voyager-frontend
Package manifest generated successfully.
Deleting Laravel's default assets, to make way for ours
Remove default welcome page
Remove default web route
Copying authentication views to main project
Copying our webpack.mix.js to the project root
Publishing the Voyager assets, database, and config files
Copied Directory [/vendor/pvtl/voyager-frontend/resources/assets] To [/resources/assets]
Publishing complete.
Updating Root package.json to include dependencies

laravel 5.6

**Comment by zeroiszero** [comment]
I got this problem as well before. the command just somehow stuck at `npm run dev` in this file https://github.com/pvtl/voyager-frontend/blob/master/src/Commands/InstallCommand.php

maybe is the `node_modules` installation taking too long and script just hanged there ? not sure.....

I overcome this by manually run `npm install` first before `composer dump-autoload && php artisan voyager-frontend:install`

if still cant solve, comment out that part and run manually.

**Comment by mcnamee** [comment]
Hi @patrickpeng830 
I believe @lukewmoore fixed this with v0.8.3
Can you please confirm?

**Comment by lukewmoore** [comment]
The install script runs some npm commands that can take a while to complete.

However with npm ^5.8/^6 on docker (maybe just non-macos machines?), even on a pure Laravel install, we can get a lot of warnings caused by the fsevents package `npm WARN rollback Rolling back ... EBUSY: resource busy or locked, unlink ...` and very slow times when using npm commands and working with an established node_modules directory, which could be the cause of our script appearing to hang. Running npm 5.6 doesn't seem to have these issues.

We could add further output during this step to confirm things are moving along.
